import type { Workflow, WorkflowStep } from '../types';
import { getConnector, getAction } from '../data/connectors';
import { getSettings } from './api';
import { baseUrlValue, baseUrlVar } from './connectorConfig';

// ── Base URL mapping ───────────────────────────────────────────────
// ── Trigger templates ──────────────────────────────────────────────
const triggerTemplates: Record<string, string> = {
  'manual': `# Trigger: Manual execution
# Run this script when you need to execute the workflow manually.
`,
  'matrix42-ticket': `# Trigger: Matrix42 ESM Ticket
# This workflow is triggered when a ticket is approved in Matrix42.
# In production, configure a Matrix42 webhook to call this script.
$ticketId = Read-Host "Enter approved Ticket ID"
`,
  'servicenow-request': `# Trigger: ServiceNow Request
# This workflow is triggered by an approved ServiceNow request.
# Configure a ServiceNow Business Rule or Flow to call this script.
$requestNumber = Read-Host "Enter ServiceNow Request Number"
`,
  'jira-request': `# Trigger: Jira Service Management Request
# This workflow is triggered by an approved Jira SM request.
$issueKey = Read-Host "Enter Jira Issue Key"
`,
};

// ── Generate PowerShell for one step ───────────────────────────────
function generateStep(step: WorkflowStep, index: number): string {
  const connector = getConnector(step.connectorId);
  const action = getAction(step.connectorId, step.actionId);
  if (!connector || !action) return `# Step ${index + 1}: Unknown action\n`;

  const varName = baseUrlVar(step.connectorId);
  const label = step.label || action.name;

  // Build the URL, replacing {param} placeholders
  let path = action.path;
  const bodyParams: Record<string, string> = {};

  for (const param of action.params) {
    const value = step.params[param.id] || param.default || '';
    if (!value) continue;

    // Cross-step references: FROM_STEP_X → $stepXResult.id in PowerShell
    let resolvedValue = value;
    const stepRefMatch = value.match(/^FROM_STEP_(\d+)$/);
    if (stepRefMatch) {
      // Use PowerShell variable reference in generated script
      // At runtime in PAMlab, the step resolver handles this
      resolvedValue = value; // Keep as-is; step resolver handles it at runtime
    }

    // Path parameters go in the URL
    if (path.includes(`{${param.id}}`)) {
      path = path.replace(`{${param.id}}`, resolvedValue);
    } else {
      bodyParams[param.id] = resolvedValue;
    }
  }

  const lines: string[] = [];
  lines.push(`# Step ${index + 1}: ${label}`);
  lines.push(`Write-Host "Step ${index + 1}: ${label}..." -ForegroundColor Cyan`);

  // Build body hashtable if we have params
  const bodyKeys = Object.keys(bodyParams);
  if (bodyKeys.length > 0 && (action.method === 'POST' || action.method === 'PUT' || action.method === 'PATCH')) {
    const stepVar = `step${index + 1}Body`;
    lines.push(`$${stepVar} = @{`);
    for (const [key, val] of Object.entries(bodyParams)) {
      // Special: members array for group actions
      if (key === 'sAMAccountName' && action.id === 'ad-add-to-group') {
        lines.push(`  members = @("${val}")`);
      } else if (val === 'true' || val === 'false') {
        // Boolean values — PowerShell $true/$false
        lines.push(`  ${key} = $${val}`);
      } else {
        lines.push(`  ${key} = "${val}"`);
      }
    }
    lines.push(`}`);
    lines.push(`$step${index + 1}Result = Invoke-RestMethod -Uri "$${varName}${path}" -Method ${action.method} -Body ($${stepVar} | ConvertTo-Json) -ContentType "application/json" -Headers $headers`);
  } else if (action.method === 'DELETE') {
    lines.push(`$step${index + 1}Result = Invoke-RestMethod -Uri "$${varName}${path}" -Method ${action.method} -Headers $headers`);
  } else {
    lines.push(`$step${index + 1}Result = Invoke-RestMethod -Uri "$${varName}${path}" -Method ${action.method} -Headers $headers`);
  }

  lines.push(`Write-Host "  ✓ Done" -ForegroundColor Green`);
  lines.push('');
  return lines.join('\n');
}

// ── Main generator ─────────────────────────────────────────────────
export function generateScript(workflow: Workflow): string {
  const settings = getSettings();
  const lines: string[] = [];

  // Header
  lines.push(`# ╔══════════════════════════════════════════════════════════════╗`);
  lines.push(`# ║  PAMlab Workflow: ${workflow.name.padEnd(41)}║`);
  lines.push(`# ║  Generated by PAMlab Studio                                 ║`);
  lines.push(`# ╚══════════════════════════════════════════════════════════════╝`);
  lines.push('');
  if (workflow.description) {
    lines.push(`# ${workflow.description}`);
    lines.push('');
  }

  // Collect unique connectors
  const usedConnectors = [...new Set(workflow.steps.map(s => s.connectorId))];

  // Base URL variables
  lines.push('# ── Configuration ──────────────────────────────────────────────');
  lines.push('# Replace these with your real environment URLs:');
  for (const cid of usedConnectors) {
    lines.push(`$${baseUrlVar(cid)} = "${baseUrlValue(cid, settings)}"`);
  }
  lines.push('');

  // Auth header
  lines.push('# Authentication (adjust to your environment)');
  lines.push(`$credentials = Get-Credential -Message "Enter service account credentials"`);
  lines.push(`$pair = "$($credentials.UserName):$($credentials.GetNetworkCredential().Password)"`);
  lines.push(`$bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)`);
  lines.push(`$base64 = [System.Convert]::ToBase64String($bytes)`);
  lines.push(`$headers = @{ Authorization = "Basic $base64" }`);
  lines.push('');

  // Error handling
  lines.push('# Error handling');
  lines.push('$ErrorActionPreference = "Stop"');
  lines.push('');

  // Trigger
  lines.push('# ── Trigger ────────────────────────────────────────────────────');
  lines.push(triggerTemplates[workflow.trigger] || triggerTemplates['manual']);

  // Steps
  lines.push('# ── Workflow Steps ─────────────────────────────────────────────');
  lines.push(`Write-Host "Starting workflow: ${workflow.name}" -ForegroundColor Yellow`);
  lines.push(`Write-Host "═══════════════════════════════════════════" -ForegroundColor Yellow`);
  lines.push('');

  for (let i = 0; i < workflow.steps.length; i++) {
    lines.push(generateStep(workflow.steps[i], i));
  }

  // Summary
  lines.push('# ── Summary ────────────────────────────────────────────────────');
  lines.push(`Write-Host "═══════════════════════════════════════════" -ForegroundColor Green`);
  lines.push(`Write-Host "Workflow '${workflow.name}' completed successfully!" -ForegroundColor Green`);
  lines.push(`Write-Host "${workflow.steps.length} steps executed." -ForegroundColor Green`);
  lines.push('');

  return lines.join('\n');
}

/** Generate a "test mode" script that runs against mock APIs (no Get-Credential) */
export function generateTestScript(workflow: Workflow): string {
  const settings = getSettings();
  const lines: string[] = [];

  lines.push(`# PAMlab Test Script — runs against mock APIs`);
  lines.push('');

  // Base URLs
  const usedConnectors = [...new Set(workflow.steps.map(s => s.connectorId))];
  for (const cid of usedConnectors) {
    lines.push(`$${baseUrlVar(cid)} = "${baseUrlValue(cid, settings)}"`);
  }
  lines.push('');

  // Simple auth
  const pair = `${settings.fudoUser}:${settings.fudoPass}`;
  const b64 = btoa(pair);
  lines.push(`$headers = @{ Authorization = "Basic ${b64}" }`);
  lines.push('');

  for (let i = 0; i < workflow.steps.length; i++) {
    lines.push(generateStep(workflow.steps[i], i));
  }

  lines.push(`Write-Host "All ${workflow.steps.length} steps done!" -ForegroundColor Green`);
  return lines.join('\n');
}
